# Generated by Django 2.2.6 on 2019-10-05 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Test', '0001_initial'),
        ('Database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('DB_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.Database')),
                ('Test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.Test')),
            ],
        ),
    ]
