# Generated by Django 2.2.6 on 2019-11-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseTest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='databasetest',
            name='Test_Duration',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
