# Generated by Django 2.2.6 on 2019-11-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseTest', '0002_databasetest_test_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='databasetest',
            name='Nb_of_done',
            field=models.IntegerField(default=0),
        ),
    ]
