# Generated by Django 2.2.6 on 2019-12-02 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseTest', '0003_databasetest_nb_of_done'),
    ]

    operations = [
        migrations.RenameField(
            model_name='databasetest',
            old_name='Nb_of_done',
            new_name='Progress',
        ),
    ]
