# Generated by Django 2.2.6 on 2019-12-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseTest', '0005_auto_20191203_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databasetest',
            name='Test_Duration',
            field=models.FloatField(default=0),
        ),
    ]
