# Generated by Django 2.2.6 on 2019-11-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='Nb_of_done',
            field=models.IntegerField(default=0),
        ),
    ]
