# Generated by Django 2.2.6 on 2019-11-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0002_test_nb_of_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='AbleToRun',
            field=models.BooleanField(default=True),
        ),
    ]
