# Generated by Django 2.2.6 on 2019-12-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0004_auto_20191201_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='AbleToRun',
        ),
        migrations.AddField(
            model_name='test',
            name='Status',
            field=models.IntegerField(default=0),
        ),
    ]
